site_name: Azure Sentinel ARM Template Automation Documentation

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src] 

nav:
  - Home: index.md
  - Reference:
      - CLI: reference/cli.md
      - Config: reference/config.md
      - Core:
          - Core Overview: reference/core.md
          - Master Loader: reference/master_loader.md
          - Playbook Loader: reference/playbook_loader.md
          - Transformer: reference/transformer.md
          - Writer: reference/writer.md
      - Utils:
          - Utils Overview: reference/utils.md
          - File System: reference/file_system.md
          - Logging Utils: reference/logging_utils.md
          - Validation: reference/validation.md
      - Template Automation: reference/template_automation.md
      - Additional:
          - Main Reference: reference/__main__.md
          - Reference Overview: reference/reference.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
